#include <pebble.h>

#if defined(PBL_COLOR)
#else
#endif

#if defined(PBL_RECT)
#define MSG_BOX_HEIGHT_DIVIDER 5
#define MSG_BOX_LAYER_X_CORRECTION_FACTOR 0
#define MSG_BOX_LAYER_Y_CORRECTION_FACTOR 0
#define BTN_DESC_WIDTH_DIVIDER 5
#define BTN_DESC_HEIGHT_DIVIDER 2.7
#define BTN_DESC_LAYER_Y_CORRECTION_FACTOR 0
#else
#define MSG_BOX_HEIGHT_DIVIDER 3.5
#define MSG_BOX_LAYER_X_CORRECTION_FACTOR 0.05
#define MSG_BOX_LAYER_Y_CORRECTION_FACTOR 0.25
#define BTN_DESC_WIDTH_DIVIDER 4
#define BTN_DESC_HEIGHT_DIVIDER 2.4
#define BTN_DESC_LAYER_Y_CORRECTION_FACTOR 0.2
#endif
#define MSG_BOX_WIDTH(x) (x-BTN_DESC_WIDTH(x))
#define MSG_BOX_HEIGHT(y) (y/MSG_BOX_HEIGHT_DIVIDER)
#define MSG_BOX_LAYER_X_CORRECTION(x) (MSG_BOX_LAYER_X_CORRECTION_FACTOR * MSG_BOX_WIDTH(x))
#define MSG_BOX_LAYER_Y_CORRECTION(y) (MSG_BOX_LAYER_Y_CORRECTION_FACTOR * MSG_BOX_HEIGHT(y))
#define BTN_DESC_WIDTH(x) (x/BTN_DESC_WIDTH_DIVIDER)
#define BTN_DESC_HEIGHT(y) (y/BTN_DESC_HEIGHT_DIVIDER)
#define BTN_DESC_X_LEFT(x) (x-(x/BTN_DESC_WIDTH_DIVIDER))
#define BTN_DESC_Y_TOP(y) (BTN_DESC_HEIGHT(y)/2)-(FONT_DEFAULT_SIZE/2)
#define BTN_DESC_LAYER_Y_CORRECTION(y) (BTN_DESC_LAYER_Y_CORRECTION_FACTOR * BTN_DESC_HEIGHT(y))

typedef enum { STATE_STANDBY, STATE_STOPPED, STATE_RUNNING, STATE_PRESET, STATE_EXPIRED } TimerState;
typedef enum { TIMER_ZERO=0, TIMER_SHORT=25, TIMER_DEFAULT=40 } Time;

typedef struct TimerInfo {
	TimerState state;
	Time startValue;
	bool isRunning;
	char *stateMessage;
} TimerInfo;

typedef struct Timer {
	const TimerInfo *info;
	Time value;
	char *valueDisplay;
	char *stateMessage;
} Timer;

const TimerInfo TIMER_STANDBY = { STATE_STANDBY, TIMER_ZERO, false, "STANDBY" };
const TimerInfo TIMER_STOPPED_DEFAULT = { STATE_STOPPED, TIMER_ZERO, false, "40'' STOPPED" };
const TimerInfo TIMER_PRESET_DEFAULT = { STATE_PRESET, TIMER_DEFAULT, false, "40'' PRESET" };
const TimerInfo TIMER_RUNNING_DEFAULT = { STATE_RUNNING, TIMER_DEFAULT, true, "40'' RUNNING" };
const TimerInfo TIMER_EXPIRED_DEFAULT = { STATE_EXPIRED, TIMER_ZERO, false, "40'' EXPIRED" };
const TimerInfo TIMER_STOPPED_SHORT = { STATE_STOPPED, TIMER_ZERO, false, "25'' STOPPED" };
const TimerInfo TIMER_PRESET_SHORT = { STATE_PRESET, TIMER_SHORT, false, "25'' PRESET" };
const TimerInfo TIMER_RUNNING_SHORT = { STATE_RUNNING, TIMER_SHORT, true, "25'' RUNNING" };
const TimerInfo TIMER_EXPIRED_SHORT = { STATE_EXPIRED, TIMER_ZERO, false, "25'' EXPIRED" };

const char *TEXT_HEADLINE = "PLAYCLOCK";
